In [110]:
from xpinyin import Pinyin
import pandas as pd
from keras.layers import LSTM
from keras.models import Sequential
import numpy as np

In [100]:
p = Pinyin()
df = pd.read_csv('ChineseNames.csv')

In [101]:
#change headers to english
df.columns = ['Name', 'Gender']

In [102]:
#strip last name
def strip_last_name(name):
    return name[1:]

def convert_to_pinyin(name):
    return p.get_pinyin(name)

def process_name(name):
    name = strip_last_name(name)
    name = convert_to_pinyin(name)
    return name

In [103]:
#visualize before after processing
print(df.tail(20))
df['Name'] = df['Name'].apply(process_name)
print(df.tail(20))

     Name Gender
9777   邹敏      F
9778  邹泞憶      F
9779  邹莎莎      F
9780  邹苇航      F
9781  邹雪飞      F
9782  邹雅文      F
9783  邹颜鞠      F
9784  邹一鑫      F
9785  邹逸宁      F
9786   邹莹      F
9787  邹滢曼      F
9788  邹雨宏      F
9789  邹雨寰      F
9790  邹玉洁      F
9791   左曈      F
9792  左婉怡      F
9793  左烜晅      F
9794  左雨晴      F
9795   左越      F
9796  左子烨      F
           Name Gender
9777        min      F
9778    ning-yi      F
9779    sha-sha      F
9780   wei-hang      F
9781    xue-fei      F
9782     ya-wen      F
9783     yan-ju      F
9784     yi-xin      F
9785    yi-ning      F
9786       ying      F
9787   ying-man      F
9788    yu-hong      F
9789    yu-huan      F
9790      yu-ji      F
9791       tong      F
9792     wan-yi      F
9793  xuan-xuan      F
9794    yu-qing      F
9795        yue      F
9796      zi-ye      F


In [104]:
#get all unique chars
characters = {}
for i, name in enumerate(df['Name']):
    for char in name:
        if char in characters:
            characters[char] += 1
        else:
            characters[char] = 1

In [105]:
#find the longest name
maxlen = df['Name'].str.len().max()

In [106]:
#create mapping.  though it would be nice if they mapping is alphabetically ordered, but it doesn't matter mathematically.
idx = 0
for c in characters.keys():
    characters[c] = idx
    idx += 1

In [163]:
#create training example of dimension (example #, timestep, # of features (length of 1-hot vector))
num_examples = df.shape[0]
time_steps = maxlen
num_features = len(characters)
def char_to_vec(char):
    vector = np.zeros((num_features, 1), dtype=int)
    idx = characters[char]
    vector[idx] = 1
    return vector

def word_to_vec(word):
    example = np.zeros((num_features, maxlen), dtype = int)
    for i in range(maxlen):
        if i < len(word):
            char = word[i]
            vector = char_to_vec(char)
            example[:,i] = vector[0]
            print(vector[:])
        else:
            example[:,i] = np.zeros((num_features),dtype=int)
    return example

In [164]:
x = word_to_vec('eafd')
print(x)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
[[0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
[[0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 

In [22]:
string.ascii_letters

'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [13]:
model = Sequential()
model.add(LSTM(1, input_shape=(50, 500), return_sequ.ences=False)
model.compile(loss='categorical_crossentropy', optimizer='adam')

Name Gender
0             yi      F
1       zhang-xi      F
2       jing-wen      F
3            lan      F
4            man      F
5       meng-yao      F
6           qiao      F
7            ran      F
8           yang      F
9             yi      F
10          ying      F
11            di      F
12           rui      F
13            di      F
14       hao-yue      F
15       hua-lin      F
16     jiao-jiao      F
17       li-qing      F
18       luo-lan      F
19       qiao-zi      F
20      qing-wen      F
21      shen-hao      F
22        yi-fan      F
23        yi-han      F
24      yue-ling      F
25           yue      F
26        zi-wei      F
27        yu-wei      F
28    cheng-yang      F
29        li-man      F
...          ...    ...
9770      ze-hao      M
9771    zhi-chao      M
9772        chen      M
9773          yi      M
9774    bao-ming      M
9775   bing-yang      M
9776     cai-wen      M
9777     hao-lin      M
9778   jia-cheng      M
9779         lei      M
9780    ming-hao      M
9781   nian-long      M
9782      shi-bo      M
9783          si      M
9784          xu      M
9785          yi      M
9786      yu-han      M
9787     zhi-gao      M
9788    zhong-yu      M
9789        zhou      M
9790      fu-hao      M
9791     xin-rui      M
9792      jia-qi      M
9793    jian-fei      M
9794    jin-ming      M
9795    kui-feng      M
9796         kun      M
9797    shi-jing      M
9798   shi-liang      M
9799    tian-you      M

[9800 rows x 2 columns]